### ISSUE TITLE
Future Development Features and recommendations

### ISSUE THREAD

**Issue by LightXEthan** [LightXEthan/uwahs-campus-map#129]
Features List: https://docs.google.com/document/d/1kpMvJaiLlomzpa7K1it8GGiX65XhJtDIS1MnrxwAlVg/edit

**Comment by LightXEthan** [comment]
We should get client approval on this.

**Comment by JKKim98** [comment]
i felt like they were expecting this. i think at one point they asked whether we were keeping track of features to be implemented in the future, not our future of course
or, perhaps i was hallucinating again~ :P
