### ISSUE TITLE
Delete point of interest

### ISSUE THREAD

**Issue by Elenaires** [LightXEthan/uwahs-campus-map#45]
- Align the existing save button to the right of the POI Edit model form (POIEditForm/index.js)
- Create a delete button and align it to the left of the form
- hook delete button to firestore for document removal
https://firebase.google.com/docs/firestore/manage-data/delete-data
- onClick, display another model on top of the POI edit model form to confirm delete 

![image](https://user-images.githubusercontent.com/16939909/64249020-493df100-cf45-11e9-806c-f44b295d67a7.png)

![image](https://user-images.githubusercontent.com/16939909/64249466-48598f00-cf46-11e9-8ccf-1097d65d6415.png)

**Comment by LightXEthan** [comment]
Closed by https://github.com/LightXEthan/uwahs-campus-map/pull/78
