### ISSUE TITLE
map-back: Uploading an image that already exists in storage will stop loading the old image

### ISSUE THREAD

**Issue by LightXEthan** [LightXEthan/uwahs-campus-map#99]

**Comment by Elenaires** [comment]
I believe this should be of high priority. Doesn't look good when images fail to load.

**Comment by Elenaires** [comment]
@LightXEthan, I am not too familiar with firebase storage but this is what I found
1) After an image is uploaded, a copy will be saved in firebase storage with the file name as name (Deleting an image from admin-front does not remove that image from storage!)
2) Uploading an image with the same name will not cause a dup in the storage thus reason for failure in loading existing images.
3) Quick fix is the upload the image not just by its name, but along with the timestamp eg:
![image](https://user-images.githubusercontent.com/16939909/66014478-a8b9fd00-e501-11e9-9b1a-ad5bbf7ccd59.png)

Let me know what you think. :)

**Comment by Elenaires** [comment]
Possibly good to add a % between filename and timestamp
![image](https://user-images.githubusercontent.com/16939909/66016445-482ebe00-e509-11e9-98b7-51c0c0b78d58.png)
Then we can extract the filename from URL and display them in our POI edit
![image](https://user-images.githubusercontent.com/16939909/66016482-6a284080-e509-11e9-80bf-ed6a5dc8c4a0.png)
![image](https://user-images.githubusercontent.com/16939909/66016513-8926d280-e509-11e9-886a-118e83817b4d.png)

**Comment by LightXEthan** [comment]
@Elenaires , I've fixed this in https://github.com/LightXEthan/uwahs-campus-map/pull/109, where images are referenced in a separate 'files' collection, and images use the same url if they are uploaded again.

You gave a better idea so I might change it but we can discuss this in the meeting today.
